services:
  - name: django-backend
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false  # Provided by Render automatically for the database
      - key: DJANGO_SECRET_KEY
        generator: secret
    autoDeploy: true

